config/routes.rb
Rails.application.routes.draw do
 	devise_for :users
 	resources :entries  do
 		resources :comments
 	end

 	resources :users, only: [:edit, :update ]
 	get 'welcome/index'
 	root 'welcome#index'

	resources :users, :path => "users" do
	member do
	  get :following, :followers
	end
	end

  	resources :relationships, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :entry
  belongs_to :user
end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :user_id, presence: true
	validates :content, presence: true
	validates :title, presence: true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower_id, presence: true
  	validates :followed_id, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :entries
    has_many :comments
	has_many :active_relationships, class_name:  "Relationship",
	                              foreign_key: "follower_id",
	                              dependent:   :destroy
	has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower


	def feed
		following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    	Entry.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
	end

	def follow(other_user)
		active_relationships.create(followed_id: other_user.id)
	end

	#unfollow a user
	def unfollow(other_user)
		active_relationships.find_by(followed_id: other_user.id).destroy
	end
	
	def following?(other_user)
		following.include?(other_user)
	end





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :user_name 
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_entry
	before_action :find_comment, only: [:destroy, :edit, :update]

	def index
		@comments = Comment.order("created_at desc").paginate(page: params[:page], per_page: 5)
	end

	def create
		@entry = Entry.find(params[:entry_id])
		@comment = @entry.comments.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.save

		redirect_to entry_path(@entry)
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to entry_path(@entry)
		else
			render 'edit'
		end
	end


	def destroy
		@entry = Entry.find(params[:entry_id])
		@comment = @entry.comments.find(params[:id])
		@comment.destroy

		redirect_to entry_path(@entry)
	end

	private
	def comment_params
		params.require(:comment).permit(:content)
	end
	def find_entry
		@entry = Entry.find(params[:entry_id])
	end

	def find_comment
		@comment = @entry.comments.find(params[:id])
	end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	before_action :find_entry, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	before_action :correct_user, only: [:edit, :destroy]
	def index
		@entries = Entry.all.order("created_at desc").paginate(page: params[:page], per_page: 3)
	end

	def new
		@entry = Entry.new
	end

	def create
		@entry = current_user.entries.build(entry_params)

		if @entry.save
			redirect_to @entry, notice: "Entry created succesfully!"
		else
			redirect_to entries_path
		end
	end

	def show
	end

	def edit 
		
	end

	def update 
		if @entry.update entry_params
			redirect_to @entry, notice: "Your article was succesfully saved!"
		else
			render 'edit'
		end
	end

	def destroy
		@entry.destroy
		redirect_to entries_path, notice: "Entry deleted!"
	end


	private

		def entry_params
			params.require(:entry).permit(:title, :content)
		end

		def find_entry
			@entry = Entry.find(params[:id])
		end

		def correct_user
			@entry = current_user.entries.find_by(id: params[:id])
			redirect_to root_url if @entry.nil?
		end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :user_signed_in?

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user}
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user}
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def edit
		@user = current_user
	end

	def index
    	@users = User.paginate(page: params[:page])
  end

	def show
		@user = User.find(params[:id])
		@etries = @user.entries.paginate(page:params[:page])
	end

	def update
		@user = current_user
		if @user.update(user_params)
			redirect_to root_path, notice: "Update profile successfully."
		else
			render :edit
		end
	end
	def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password,
  									:password_confirmation)
  	end

    #before filters

    #confirms a logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

    #confirms the correct user
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

    #confirms an admin user
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

	private
	def user_params
		params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@entries = Entry.all.limit(3).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.user.email %></strong></p>
    <p class="comment_time"><< <%= comment.created_at.strftime('%e %b,  %Y | %H:%M:%S%p') %>  >></p>
    <p class="comment_body"><%= comment.content %></p>
    
  </div>

  <% if user_signed_in? && (current_user.id == comment.user_id) %>
  <p><%= link_to 'Delete', [comment.entry, comment],
                  method: :delete,
                  class: "button",
                  data: { confirm: 'Are you sure?' } %>
                    
      <%= link_to 'Edit', edit_entry_comment_path(comment.entry,comment),
                  class: "button" %>
  </p>
  <p>---------------------------------------------</p>

  <% end %>

</div>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
	<h3>Add a comment:</h3>
	<%= form_for([@entry, @entry.comments.build]) do |f| %>
		<p>
			<%= f.text_area :content %>
		</p>
		<p> <%= f.submit %></p>
	<% end %>
<% end %>

app/views/comments/edit.html.erb
<%= form_for([@entry, @comment]) do |f| %>
	<p><%= f.text_area :content %></p>
	<p><%= f.submit %></p>
<% end %>

app/views/comments/new.html.erb
<h1 id="page_title">comment</h1>
<%= render 'form' %>

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>
	<% if @entry.errors.any? %>
		<h2><%= pluralize(@entry.errors.count, "error") %> prevented this from saving:</h2>
		<ul>
			<% @entry.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>
	<br>
	<br>
	<%= f.label :title, "Write your article here" %><br>
	<%= f.text_area :content %>

	<br>
	<br>
	<%= f.submit %>
<% end %>

app/views/entries/edit.html.erb
<h1 id="page_title">Edit Entry</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/entries/index.html.erb
<h1 id="page_title">All Entries</h1>

<div id="posts_wrapper" class="skinny_wrapper">
	<% @entries.each do |entry| %>
		<div class="post">
			<p class="date"><%= entry.created_at.strftime('%A, %B %d') %></p>
			<h2><a href="#"><%= link_to entry.title, entry %></a></h2>
			<hr>
		</div>
	<% end %>
</div>

	<%= will_paginate @entries %>

app/views/entries/new.html.erb
<h1 id="page_title">New Entry</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/entries/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @entry.created_at.strftime('%A, %B %d') %></p>
		<p class="date"><%= @entry.user.user_name || @entry.user.email %></p>
		<h1><%= @entry.title %></h1>
		<hr>
	</header>

	<div id="content">
		<%=  simple_format @entry.content %>
	</div>
	<% if (current_user && @entry == current_user.entries.find_by(id: params[:id])) %>
		<div id="admin_links">
			<%= link_to "Edit Entry", edit_entry_path(@entry) %>
			<%= link_to "Delete Entry", entry_path(@entry), method: :delete, data: { confirm: "Are you sure?" } %>
		</div>
	<% end %>
		<hr>
		<div id="comment">
			<h2><%= pluralize(@entry.comments.count, "comment") %></h2>
			<%= render @entry.comments %>


			<%= render"comments/form" %>
		</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>QuynhBlog</title>
	<link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header id="main_navigation" class="clearfix">
		<%= link_to "Q_Blog", root_path, class: "name" %>
		<nav>
			<%if user_signed_in?%>
			Logged in as <strong><%= current_user.user_name || current_user.email %></strong>.
			<%= link_to 'Users', users_path %> |
			<%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> |
			<% end %>
			<%= link_to "All Entries", entries_path %> |
			<%if not user_signed_in?%>
				<%= link_to "Sign up", new_user_registration_path %>|
				<%= link_to "Sign in", user_session_path %>
			<% end %>
			
			<%if user_signed_in?%>
				<%= link_to "New Entry", new_entry_path %>
				<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
			<% end %>
			

		</nav>
	</header>

	<% if notice %>
		<p class="notice"><%= notice %></p>
	<% elsif alert %>
		<p class="alert"><%= alert %></p>
	<% end %>

	<%= yield %>

	<footer id="main_footer">
		<p class="copyright">2016 QuynhBlog</p>
		<nav>
			<a href="#" ><i class="fa fa-twitter"></i></a>
			<a href="#" ><i class="fa fa-dribbble"></i></a>
			<a href="#" ><i class="fa fa-github"></i></a>
		</nav>
	</footer>

</body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remtote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.id == @user.id %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_unfolow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= link_to user.user_name, user %>
</li>

app/views/users/edit.html.erb
 <div class="skinny_wrapper wrapper_padding">
  <h1>Editing Profile</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this idea from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :user_name %><br>
      <%= f.text_field :user_name %>
    </div>
    <div class="field">
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1 id="page_title"> All Users </h1>

<div id="posts_wrapper" class="skinny_wrapper">
	<% @users = User.all %>
	<% @users.each do |user| %>
	  <p>ID: <%= user.id %><br>
	  Email: <%= link_to user.email, user_path(user)%></p>
	<% end %>
</div>

app/views/users/show.html.erb
<div id="posts_wrapper" class="skinny_wrapper">
        <h1><%= @user.user_name || @user.email %></h1>
        <%= render 'shared/stats' %>
        <%= render 'follow_form' if user_signed_in? %>


      <% if @user.entries.any? %>
        <h3>Entries (<%= @user.entries.count %>)</h3>
        <ol class="microposts">
          <% @user.entries.each do |entry| %>
            <%= link_to entry.title, entry_path(entry) %><br>
          <%end %>
        </ol>
      <% end %>
</div>

app/views/users/show_follow.html.erb
<div id="posts_wrapper" class="skinny_wrapper">
  <% provide(:title, @title) %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1><%= @user.user_name || @user.email %></h1>
        <span><%= link_to "View profile", @user %></span><br><br>
        <span><b>Entries:</b> <%= @user.entries.count %></span>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
        
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= @title %></h3>
      <% if @users.any? %>
        <ul class="users follow">
          <%= render @users %>
        </ul>
        <%= will_paginate %>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
	<div class="col-1 about homepage_content">
		<h2>About</h2>
		<hr>
		<p>Hello world</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla massa nisl, convallis ut ipsum sed, faucibus luctus sem. Mauris ac ex eget lectus iaculis efficitur eget et tellus. Mauris metus est, imperdiet vitae pellentesque ut, hendrerit vitae leo. Suspendisse mollis rhoncus sodales. </p>
		
	</div>

	<div class="col-2 homepage_content">
		<h2>Entries</h2>
		<hr>
		<% @entries.each do |entry| %>
			<h3><a href="#"><%= link_to entry.title, entry %></a></h3>
			<p class="date"><%= entry.created_at.strftime("%A, %b %d") %></p>
		<% end %>
		
	</div>

	<div class="col-3 homepage_content">
		
	</div>
	
</div>